### ISSUE TITLE
Fails to create AWX API token

### ISSUE THREAD

**Issue by PC-Admin** [PC-Admin/awx-ansible#1]
This section of cleanup_defaults.yml fails:
```
- name: Create a AWX/Automation Controller session token for executing AWX modules
  awx.awx.tower_token:
    description: 'AWX/Automation Controller Session Token'
    scope: "write"
    state: present
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ master_token }}"
    validate_certs: yes
  register: awx_session_token
```

causes:
```
TASK [awx-custom-config : Create a AWX/Automation Controller session token for executing AWX modules] *********************************************************************************
fatal: [awx.penholder.xyz]: FAILED! => {"changed": false, "msg": "There was an unknown error when trying to connect to https://awx.penholder.xyz/api/v2/tokens/: URLError <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:997)>"}
```
